### ISSUE TITLE
LogAllConnectionStrings message is corrupted on damaged connection string

### ISSUE THREAD

**Issue by colinangusmackay** [Stravaig-Projects/Stravaig.Extensions.Configuration.Diagnostics#159]
If the connection string cannot be interpreted by the Connection String builder then the message is corrupted with placeholder names.

The exception is correctly rendered, but parts of the message are incorrect.

```
[13:18:15 WRN] The following connection strings were found: ["DealStackerContext", "DistCache", "DealStackerContext", "DistCache"], {preamble_DistCache_name}.
The "{DealStackerContext_name}" connection string value could not be interpreted as a connection string.
The "{DistCache_name}" connection string value could not be interpreted as a connection string.

System.AggregateException: Multiple errors occurred when rendering the connection strings. (Format of the initialization string does not conform to specification starting at index 0.) (Format of the initialization string does not conform to specification starting at index 0.)
 ---> System.ArgumentException: Format of the initialization string does not conform to specification starting at index 0.
   at System.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, Int32 currentPosition, StringBuilder buffer, Boolean useOdbcRules, String& keyname, String& keyvalue)
   at System.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey)
   at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms, Boolean useOdbcRules)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Stravaig.Configuration.Diagnostics.Renderers.StructuredConnectionStringRenderer.Render(String connectionString, String name, ConfigurationDiagnosticsOptions options)
   --- End of inner exception stack trace ---
 ---> (Inner Exception #1) System.ArgumentException: Format of the initialization string does not conform to specification starting at index 0.
   at System.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, Int32 currentPosition, StringBuilder buffer, Boolean useOdbcRules, String& keyname, String& keyvalue)
   at System.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey)
   at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms, Boolean useOdbcRules)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Stravaig.Configuration.Diagnostics.Renderers.StructuredConnectionStringRenderer.Render(String connectionString, String name, ConfigurationDiagnosticsOptions options)<---

```

**Comment by colinangusmackay** [comment]
This only happens when there are two or more bad connection strings
